### ISSUE TITLE
Docker image and container storage space

### ISSUE THREAD

**Issue by timhowes** [nturaga/BioconductorOnContainers#2]
https://github.com/nturaga/BioconductorOnContainers/blob/d432a5a31eb89a54fba168e4d7118374625be21e/vignettes/Bioconductor_Containers_Workshop.Rmd#L61-L66

My understanding is this is not the case. Docker makes use of copy-on-write technology wherever possible, so that files from the image are not duplicated when you start a container. In fact, you can use `docker system df -v` to see the actual space usage for individual containers, which is usually quite low.

https://medium.com/@nagarwal/docker-containers-filesystem-demystified-b6ed8112a04a
https://docs.docker.com/v17.09/engine/userguide/storagedriver/imagesandcontainers/
https://docs.docker.com/engine/reference/commandline/system_df/

**Comment by nturaga** [comment]
Hi @timhowes 

Thanks for pointing this out. I'll take a look at it and fix it. I'll use this statement instead

"The total disk space used by all of the running containers on disk is some combination of each 
container’s size and the virtual size values. If multiple containers started from the same exact image, the total size on disk for these containers would be SUM (size of containers) plus one container’s (virtual size- size)."

**Comment by nturaga** [comment]
This is now fixed. I'm closing the issue. Thank you for pointing this out to me!
